import os
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from core.workflow import build_workflow
from core.types import AgentState
import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel
from fastapi import HTTPException
from langchain_core.messages import HumanMessage
from langchain_core.exceptions import OutputParserException
from google.api_core.exceptions import GoogleAPIError
import traceback

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

app = FastAPI()

client = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=GEMINI_API_KEY
)

workflow = build_workflow(client)


state: AgentState = {
    "messages": [],
    "last_events": None,
    "last_emails": None,
    "conversation_summary": None,
    "summarized_message_count": 0,
}
class UserRequest(BaseModel):
    message: str

@app.get("/")
def normal():
    return {"response": "Go to docs for inspection"}

@app.post("/send")
def send_response(user_request: UserRequest):
    global state

    try:
        state = workflow.invoke({
            "messages": state["messages"] + [
                HumanMessage(content=user_request.message)
            ],
            "last_events": state.get("last_events"),
            "last_emails": state.get("last_emails"),
            "conversation_summary": state.get("conversation_summary"),
            "summarized_message_count": state.get("summarized_message_count", 0),
        })

        last_message = state["messages"][-1]

        if not hasattr(last_message, "content") or not last_message.content:
            raise HTTPException(
                status_code=500,
                detail={
                    "error": "EMPTY_RESPONSE",
                    "message": "No response generated by workflow."
                }
            )

        if isinstance(last_message.content, str):
            return {"response": last_message.content}

        return {
            "response": "".join(
                part.get("text", "")
                for part in last_message.content
                if isinstance(part, dict)
            )
        }

    except GoogleAPIError  as e:
        raise HTTPException(
            status_code=502,
            detail={
                "error": "MODEL_API_ERROR",
                "message": str(e)
            }
        )

    except OutputParserException as e:
        raise HTTPException(
            status_code=500,
            detail={
                "error": "WORKFLOW_PARSING_ERROR",
                "message": str(e)
            }
        )

    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail={
                "error": "BAD_REQUEST",
                "message": str(e)
            }
        )
    
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(
            status_code=500,
            detail={
                "error": "INTERNAL_SERVER_ERROR",
                "message": "Unexpected server error.",
                "debug": str(e)
            }
        )

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=3000)